<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[25]=array(0,-19,1,'5YGH6K+E6K66');
$cfg_Cs[21]=array(12,1,1,'5rGC5ama5oiS5oyH');
$cfg_Cs[16]=array(12,1,1,'5rGC5ama562W5YiS');
$cfg_Cs[17]=array(12,1,1,'5rGC5ama5Yib5oSP');
$cfg_Cs[18]=array(12,1,1,'5rGC5ama5pa55byP');
$cfg_Cs[19]=array(12,1,1,'5rGC5ama5q2M5puy');
$cfg_Cs[20]=array(12,1,1,'5rGC5ama6K+N');
$cfg_Cs[14]=array(0,17,1,'5rGC5ama5qGI5L6L');
$cfg_Cs[22]=array(0,6,1,'5ZWG5Z+O');
$cfg_Cs[15]=array(0,18,1,'5rGC5ama6KeG6aKR');
$cfg_Cs[12]=array(0,1,1,'5rGC5ama');
?>