<field:body itemname="详细介绍（场景布置）" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	
<field:price itemname="市场价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:price>	
<field:trueprice itemname="优惠价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:trueprice>	
<field:brand itemname="品牌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:brand>	
<field:units itemname="计量单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:units>	
	
<field:vocation itemname="行业" autofield="1" notsend="0"type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:vocation>	
<field:infotype itemname="信息类型" autofield="1" notsend="0" type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:infotype>	
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
<field:pricemax itemname="市场价Max" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pricemax>
<field:truepricemax itemname="优惠价Max" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:truepricemax>
<field:defined1 itemname="主题寓意" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:defined1>
<field:video itemname="参考视频" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:video>
<field:defined3 itemname="适用场景" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:defined3>



<field:details1 itemname="大型升降高档舞台承重桁架" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details1>

<field:details2 itemname="舞台浪漫路引木质装饰T台" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details2>

<field:details3 itemname="200W静音主板液晶显示万能通道电脑光束灯一套" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details3>

<field:details4 itemname="高级跑马流水刷新复位全彩遥控帕灯一套" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details4>

<field:details5 itemname="高显色指数LED集成面光筒灯一套" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details5>

<field:details6 itemname="200米射程追光灯" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details6>

<field:details7 itemname="闪光反射镜面旋转球舞台灯" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details7>

<field:details8 itemname="LED引路RGB七彩遥控彩色射灯" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details8>

<field:details9 itemname="LED圆球彩色珍珠串灯" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details9>

<field:details10 itemname="大型3D舞台专属设计背景喷绘" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details10>

<field:details11 itemname="碳化防腐栅栏场景围栏装饰" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="否,是"  maxlength="250" page="">
</field:details11>
