
    <m:item name='客户反馈' ischannel='1' link='content_sg_list.php?channelid=-30' linkadd='archives_sg_add.php?channelid=-30' channelid='-30' rank='' target='main' />
  <m:item name='假评论' ischannel='1' link='content_sg_list.php?channelid=-19' linkadd='archives_sg_add.php?channelid=-19' channelid='-19' rank='' target='main' />
  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='商品' ischannel='1' link='content_list.php?channelid=6' linkadd='archives_add.php?channelid=6' channelid='6' rank='' target='main' />
  <m:item name='视频' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add.php?channelid=18' channelid='18' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
