<li>
                        <a class="news" href="/m[field:arcurl/]">
                            <div class="pic">
                                <img src="[field:litpic/]"/>
                            </div>
                            <div class="project_cont">
                                <h5>[field:title/]</h5>
                            </div>
                            <div class="price">
                                <p>2015/04/16</p>
                                <span>[field:click/]</span>
                                <i class="am-icon-eye"></i>
                                <div class="clear"></div>
                            </div>
                        </a>
                    </li>