<dl>
			<dd class="tit"><a href="[field:arcurl/]" target="_blank" rel="nofollow">[field:title/]</a></dd>
			<dt><a href="[field:arcurl/]" target="_blank" rel="nofollow"><img src="[field:litpic/]" title="[field:title/]"></a></dt>
			<dd class="pri"><em>¥[field:trueprice/][field:truepricemax runphp="yes"]if(empty(@me)){@me="";}else{@me=" - ".@me;}[/field:truepricemax]</em><span><a href="tencent://message/?uin=3547038718&Site=qq&Menu=yes" target="_blank" rel="nofollow">预定</a></span></dd>
		</dl>