<li class="view">
            <a href="/m[field:arcurl/]">
                <div class="pic">
                    <img src="[field:litpic/]">
                    <div class="clear"></div>
                </div>
                <div class="con">
                    <h5>[field:title/]</h5>
                    <p>[field:description function='cn_substr(@me,250)' /]...</p>
                </div>
            </a>
        </li>