<li>
				<img src="[field:litpic/]">
				<span>[field:username/]</span>
				<p>[field:body/]</p>
			</li>
			<li>
				<img src="http://www.one-meet.com/wp-content/uploads/bfi_thumb/tx8-n94zidclzcgmtb57axdu8e17dix8m22jxt7uwxw14o.jpg">
				<span>花开叶落</span>
				<p>非常感谢小刘策划师，为我们的爱情量身定制的求婚创意非常棒。感谢TheOne求婚公司的现场的耐心指导和安排</p>
			</li>
			<li>
				<img src="http://www.one-meet.com/wp-content/uploads/bfi_thumb/tx8-n94zidclzcgmtb57axdu8e17dix8m22jxt7uwxw14o.jpg">
				<span>花开叶落</span>
				<p>非常感谢小刘策划师，为我们的爱情量身定制的求婚创意非常棒。感谢TheOne求婚公司的现场的耐心指导和安排</p>
			</li>
			<li>
				<img src="http://www.one-meet.com/wp-content/uploads/bfi_thumb/tx8-n94zidclzcgmtb57axdu8e17dix8m22jxt7uwxw14o.jpg">
				<span>花开叶落</span>
				<p>非常感谢小刘策划师，为我们的爱情量身定制的求婚创意非常棒。感谢TheOne求婚公司的现场的耐心指导和安排</p>
			</li>
			<li>
				<img src="http://www.one-meet.com/wp-content/uploads/bfi_thumb/tx8-n94zidclzcgmtb57axdu8e17dix8m22jxt7uwxw14o.jpg">
				<span>花开叶落</span>
				<p>非常感谢小刘策划师，为我们的爱情量身定制的求婚创意非常棒。感谢TheOne求婚公司的现场的耐心指导和安排</p>
			</li>