<?php
$z[0]=Array("item","",4,98);
$z[0][4]['name']="一键更新网站";
$z[0][4]['link']="makehtml_all.php";
$z[0][4]['rank']="sys_MakeHtml";
$z[0][4]['target']="main";
$z[1]=Array("item","",102,204);
$z[1][4]['name']="一键更新移动网站";
$z[1][4]['link']="makehtml_all_m.php";
$z[1][4]['rank']="sys_MakeHtml";
$z[1][4]['target']="main";
$z[2]=Array("item","",208,302);
$z[2][4]['name']="更新系统缓存";
$z[2][4]['link']="sys_cache_up.php";
$z[2][4]['rank']="sys_ArcBatch";
$z[2][4]['target']="main";

?>