<li>
            <a class="news" href="news_detail.html">
                <div class="pic">
                    <img src="[field:litpic/]"/>
                </div>
                <div class="project_cont">
                    <p>[field:title/]</p>
                </div>
                <div class="price">
                    <p>[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                    <span>[field:click/]</span>
                    <i class="am-icon-eye"></i>
                    <div class="clear"></div>
                </div>
            </a>
        </li>