<field:body itemname="详细介绍（场景布置）" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	
<field:price itemname="市场价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:price>	
<field:trueprice itemname="优惠价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:trueprice>	
<field:brand itemname="品牌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:brand>	
<field:units itemname="计量单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:units>	
	
<field:vocation itemname="行业" autofield="1" notsend="0"type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:vocation>	
<field:infotype itemname="信息类型" autofield="1" notsend="0" type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:infotype>	
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
<field:pricemax itemname="市场价Max" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pricemax>
<field:truepricemax itemname="优惠价Max" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:truepricemax>
<field:defined1 itemname="主题寓意" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:defined1>

<field:video itemname="参考视频" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:video>

<field:defined2 itemname="其他服务" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:defined2>
<field:defined3 itemname="适用场景" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:defined3>

<field:defined4 itemname="服务明细" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="大型升降高档舞台承重桁架,大型炫彩舞台可升降灯光专用T形架一套,200W静音主板液晶显示万能通道电脑光束灯一套"  maxlength="250" page="">
</field:defined4>
