<li class="view">
            <a href="/m[field:arcurl/]">
                <div class="pic">
                    <img src="[field:litpic/]">
                    <div class="cont">
						<span class="button xq">¥[field:trueprice/]起</span>
						<div class="num">
							<p><span>20/30</span>人报名</p>
							<p>出发时间<span>2017/10/02</span></p>
						</div>
					</div>
                    <div class="clear"></div>
                </div>
                <div class="con">
                    <h5>[field:title/]</h5>
                    <p>[field:description function='cn_substr(@me,250)' /]...</p>
                </div>
            </a>
        </li>