<li class="view">
                        <a href="[field:arcurl/]">
    						<div class="pic">
    							<img src="[field:litpic/]">
    							<div class="cont">
    								<span class="button xq">¥[field:trueprice/]起</span>
    								<!-- <div class="num">
    									<p><span>20/30</span>人报名</p>
    									<p>出发时间<span>2017/10/02</span></p>
    								</div> -->
    							</div>
    							<div class="clear"></div>
    						</div>
    						<div class="con">
    							<span>[field:title/]</span>
    							<p>卫坡古民居翠湾果岭观唐生态园炎帝本草园洛阳粤钰青...</p>
    						</div>
                        </a>
					</li>