<div class="_item">
<div class="_item_label ui-nowrap">[field:title/]</div>
<a href="[field:arcurl/]" title="[field:title/]" target="_blank">
<img src="[field:image/]" class="lazy" alt="[field:title/]"/>
</a>
<div class="_item_footer">
<span class="price">¥[field:trueprice/]-[field:truepricemax/]</span>
<a class="order" target="_blank" href="/romantic/confirm.html?mall=[field:id/]">预定</a>
</div>
</div>