<li class="view">
                        <a href="/m[field:arcurl/]">
                            <div class="pic">
                                <img src="[field:litpic/]">
                                <div class="cont">
                                    <span class="button xq">¥[field:trueprice/]起</span>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="con">
                                <h5>[field:title/]</h5>
                                <p>卫坡古民居翠湾果岭观唐生态园炎帝本草园洛阳粤钰青...</p>
                            </div>
                        </a>
                    </li>