<?php
$z[0]=Array("global","",106,134);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",1472,1497);
$z[1][4]['name']="cfg_static";
$z[2]=Array("global","",1582,1607);
$z[2][4]['name']="cfg_static";
$z[3]=Array("global","",1687,1712);
$z[3][4]['name']="cfg_static";
$z[4]=Array("global","",1785,1810);
$z[4][4]['name']="cfg_static";
$z[5]=Array("global","",1847,1873);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("arclist","\r\n<a href=\"[field:arcurl/]\" target=\"_blank\">\r\n<img src=\"images/placeholder.png\" class=\"lazy\" data-original=\"[field:image/]\" alt=\"[field:title/]\"/>\r\n<span class=\"fixed-title\">[field:title/]</span>\r\n</a>",8950,9196);
$z[6][4]['row']="6";
$z[6][4]['typeid']="14";
$z[7]=Array("arclist","\r\n<div class=\"_item\">\r\n<div class=\"_item_label ui-nowrap\">[field:title/]</div>\r\n<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">\r\n<img src=\"[field:litpic/]\" class=\"lazy\" alt=\"[field:title/]\"/>\r\n</a>\r\n<div class=\"_item_footer\">\r\n<span class=\"price\">¥[field:trueprice/]-[field:truepricemax/]</span>\r\n<a class=\"order\" target=\"_blank\" href=\"/romantic/confirm.html?mall=[field:id/]\">预定</a>\r\n</div>\r\n</div>",9338,9854);
$z[7][4]['row']="8";
$z[7][4]['typeid']="22";
$z[7][4]['addfields']="trueprice,truepricemax";
$z[7][4]['channelid']="6";

?>