CREATE TABLE IF NOT EXISTS `dede_user_action`(
   `id` INT(10) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
   `user_id` INT(10) NOT NULL COMMENT '会员ID',
   `type` VARCHAR(50) NOT NULL COMMENT '类型',
   `os` VARCHAR(50) NOT NULL COMMENT '凭证',
   `time` INT(10) NULL COMMENT '标识',
   `ip` VARCHAR(20) NOT NULL COMMENT '凭证',
   `realip` VARCHAR(20) NOT NULL COMMENT '凭证',
   PRIMARY KEY ( `id` )
)ENGINE=MyISAM DEFAULT CHARSET=utf8;